name: Trigger Lambda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke Lambda
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: example_function
          Payload: '{"name": "GitHub Actions"}'